services:
  strata:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: strata
    image: strata:live
    ports:
      - 8080:8080
    working_dir: /opt/strata
    volumes:
      - ./:/opt/strata

  postgres:
    image: postgres:latest
    container_name: strata_psql
    expose:
      - 5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: strata
      POSTGRES_USER: strata
      POSTGRES_PASSWORD: atarts
