# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Unit Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Start postgres with init script
      run: |
        docker run -d --name my-postgres \
          -e POSTGRES_DB=strata \
          -e POSTGRES_USER=strata \
          -e POSTGRES_PASSWORD=atarts \
          -v ${{ github.workspace }}/schema:/docker-entrypoint-initdb.d \
          -p 5432:5432 \
          postgres
          
    - name: Wait for Postgres
      run: |
        until docker exec my-postgres pg_isready; do
          echo "Waiting for postgres..."
          sleep 2
        done
        
    - name: Run SQL commands
      run: |
        psql -h postgres -c 'BEGIN TRANSACTION;' -f database/1_schema.sql -f database/2_data.sql -c 'COMMIT;'
      env:
        PGPASSWORD: atarts

    - name: Run Database Migrations
      run: docker exec postgres psql -c "BEGIN TRANSACTION;" -f database/1_schema.sql -f database/2_data.sql -c "COMMIT;" postgresql://strata:atarts@postgres:5432/strata

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Install Dependencies
      run: go get ./cmd

    - name: Build
      run: go build -o strata -v ./cmd

    - name: Test
      run: go test -v ./pkg/test
      env: 
        POSTGRES_HOST: postgres
        DB_HOSTNAME: postgres
        DB_USERNAME: strata
        DB_PASSWORD: atarts
        DB_DATABASE: strata
        DB_PORT: 5432
      


